[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_BASE = "https://rocher-party-production.up.railway.app/api"
